dist: trusty
sudo: required

notifications:
  email: true

services:
  - docker

language: c

before_install:
  - git clone https://github.com/sancus-pma/sancus-main.git
  - cd sancus-main/docker && make build

script:
  - docker run sancus-devel /bin/sh -c \
        "cd /sancus/sancus-examples && git checkout $TRAVIS_BRANCH &&
         make $TARGET.sim"
  - docker ps -a

env:
  - TARGET=hello-world
  - TARGET=sensor-reader
  - TARGET=arithmetic
  - TARGET=fileio
